language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - addon-google_apis-google-19
    - extra-google-play_billing

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  ./gradlew clean app:assembleDebug app:testDebug